steamos-manager: Fix TDP controls not showing up
The latest version added the `EnvironmentFile` key to the user service.
Since CachyOS doesn't have this, that service will presumably fail to
start and users will see errors like

    Error: org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'com.steampowered.SteamOSManager1': startup job failed

Fix this by patching out the line.

Signed-off-by: Eric Naim <dnaim@cachyos.org>